name: jcache
description: Jireh Cache Management - Complete solution for efficient caching and total control over your files and data.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^1.3.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
